sudo: false
addons:
  apt:
    packages:
      - aspell
language: perl
perl:
  - blead       # builds perl from git
  - dev         # latest point release
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
env:
  matrix:
    - USE_BUILD_PL=1
    - USE_MAKEFILE_PL=1
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=0
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
script:
  - if [ $USE_BUILD_PL ] ; then
      perl Build.PL; ./Build;
    else
      PERL_MM_FALLBACK_SILENCE_WARNING=1 perl Makefile.PL; make;
    fi
  - prove -b -r -s -j$(test-jobs) $(test-files)
